name: permission_handler_web
description: My implementation of web part for permission_handler
version: 0.0.2
repository: https://github.com/johnwcchau/permission_handler_web

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  permission_handler_platform_interface: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: PermissionHandlerWeb
        fileName: permission_handler_web.dart
